name: First Actions Workflow
on: workflow_dispatch
jobs:
  first_job: 
    runs-on: unbuntu-latest
    steps:
    - name: Print salutation
      run: echo "Salutaion fellas !"
    - name: Parting shots
      run: echo "Se ya' later aligator"
    
